const data = [
    {id: 1, v1: 'abide', v2: 'abode/abided', v3:'abode/abided', trans:'lưu trú, lưu lại'},
    {id: 2 , v1: 'arise', v2: 'arose', v3:'arisen', trans:'phát sinh'},
    {id: 3 , v1: 'awake', v2: 'awoke', v3:'awoken', trans:'đánh thức, thức'},
    {id: 4 , v1: 'backslide', v2: 'backslid', v3:'backslidden/backslid', trans:'tái phạm'},
    {id: 5 , v1: 'be', v2: 'was/were', v3:'been', trans:'	thì, là, bị, ở'},
    {id: 6 , v1: 'bear', v2: 'bore', v3:'borne', trans:'mang, chịu đựng'},
    {id: 7 , v1: 'beat', v2: 'beat', v3:'beaten/beat', trans:'đánh, đập'},
    {id: 8 , v1: 'become', v2: 'became', v3:'become', trans:'trở nên'},
    {id: 9 , v1: 'befall', v2: 'befell', v3:'befallen', trans:'xảy đến'},
    {id: 10 , v1: 'begin', v2: 'began', v3:'begun', trans:'bắt đầu'},
    {id: 11 , v1: 'behold', v2: 'beheld', v3:'beheld', trans:'ngắm nhìn'},
    {id: 12 , v1: 'bend', v2: 'bent', v3:'bent', trans:'bẻ cong'},
    {id: 13 , v1: 'beset', v2: 'beset', v3:'beset', trans:'	bao quanh'},
    {id: 14 , v1: 'bespeak', v2: 'bespoke', v3:'bespoken', trans:'chứng tỏ'},
    {id: 15 , v1: 'bet', v2: 'bet/betted', v3:'bet/betted ', trans:'đánh cược, cá cược'},
    {id: 16 , v1: 'bid', v2: 'bid', v3:'bid', trans:'trả giá'},
    {id: 17 , v1: 'bind', v2: 'bound', v3:'bound', trans:'buộc, trói'},
    {id: 18 , v1: 'bite', v2: 'bit', v3:'bitten', trans:'cắn'},
    {id: 19 , v1: 'bleed', v2: 'bled', v3:'bled', trans:'chảy máu'},
    {id: 20 , v1: 'blow', v2: 'blew', v3:'blown', trans:'thổi'},
    {id: 21 , v1: 'break', v2: 'broke', v3:'broken', trans:'đập vỡ'},
    {id: 22 , v1: 'breed', v2: 'bred', v3:'bred', trans:'nuôi, dạy dỗ'},
    {id: 23 , v1: 'bring', v2: 'brought', v3:'brought', trans:'mang đến'},
    {id: 24 , v1: 'broadcast', v2: 'broadcast', v3:'broadcast', trans:'phát thanh'},
    {id: 25 , v1: 'browbeat', v2: 'browbeat', v3:'browbeaten/browbeat', trans:'hăm dọa'},
    {id: 26 , v1: 'build', v2: 'built', v3:'built', trans:'xây dựng'},
    {id: 27 , v1: 'burn', v2: 'burnt/burned', v3:'burnt/burned', trans:'đốt, cháy'},
    {id: 28 , v1: 'burst', v2: 'burst', v3:'burst', trans:'nổ tung, vỡ òa'},
    {id: 29 , v1: 'bust', v2: 'busted/bust', v3:'busted/bust', trans:'làm bể, làm vỡ'},
    {id: 30 , v1: 'buy', v2: 'bought', v3:'bought', trans:'mua'},
    {id: 31 , v1: 'cast', v2: 'cast', v3:'cast', trans:'ném, tung'},
    {id: 32 , v1: 'catch', v2: 'caught', v3:'caught', trans:'bắt, chụp'},
    {id: 33 , v1: 'chide', v2: 'chid/chided', v3:'chid/chidden/chided', trans:'mắng, chửi'},
    {id: 34 , v1: 'choose', v2: 'chose', v3:'chosen', trans:'chọn, lựa'},
    {id: 35 , v1: 'cleave', v2: 'clove/cleft/cleaved', v3:'cloven/cleft/cleaved', trans:'chẻ, tách hai'},
    {id: 36 , v1: 'cleave', v2: 'clave', v3:'cleaved', trans:'dính chặt'},
    {id: 37 , v1: 'cling', v2: 'clung', v3:'clung', trans:'bám vào, dính vào'},
    {id: 38 , v1: 'clothe', v2: 'clothed/clad', v3:'clothed/clad', trans:'che phủ'},
    {id: 39 , v1: 'come', v2: 'came', v3:'come', trans:'đến, đi đến'},
    {id: 40 , v1: 'cost', v2: 'cost', v3:'cost', trans:'có giá là'},
    {id: 41 , v1: 'creep', v2: 'crept', v3:'crept ', trans:'bò, trườn, lẻn'},
    {id: 42 , v1: 'crossbreed', v2: 'crossbred', v3:'crossbred', trans:'cho lai giống'},
    {id: 43 , v1: 'crow', v2: 'crew/crewed', v3:'crowed', trans:'gáy (gà)'},
    {id: 44 , v1: 'cut', v2: 'cut', v3:'cut', trans:'	cắt, chặt'},
    {id: 45 , v1: 'daydream', v2: 'daydreamed/daydreamt', v3:'daydreamed/daydreamt', trans:'nghĩ vẩn vơ, mơ mộng'},
    {id: 46 , v1: 'deal', v2: 'dealt', v3:'dealt', trans:'giao thiệp'},
    {id: 47 , v1: 'dig', v2: 'dug', v3:'dug', trans:'đào'},
    {id: 48 , v1: 'disprove', v2: 'disproved', v3:'disproved/disproven', trans:'bác bỏ'},
    {id: 49 , v1: 'dive', v2: 'dove/dived', v3:'dived', trans:'lặn, lao xuống'},
    {id: 50 , v1: 'do', v2: 'did', v3:'done', trans:'làm'},
    {id: 51 , v1: 'draw', v2: 'drew', v3:'', trans:''},
    {id: 52 , v1: 'dream', v2: 'dreamt/dreamed', v3:'dreamt/dreamed', trans:'mơ thấy'},
    {id: 53 , v1: 'drink', v2: 'drank', v3:'drunk', trans:'uống'},
    {id: 54 , v1: 'drive', v2: 'drove', v3:'driven', trans:'lái xe'},
    {id: 55 , v1: 'dwell', v2: 'dwelt', v3:'dwelt', trans:'trú ngụ, ở'},
    {id: 56 , v1: 'eat', v2: 'ate', v3:'eaten', trans:'ăn'},
    {id: 57 , v1: 'fall', v2: 'fell', v3:'fallen', trans:'ngã, rơi'},
    {id: 58 , v1: 'feed', v2: 'fed', v3:'fed', trans:'cho ăn, ăn, nuôi'},
    {id: 59 , v1: 'feel', v2: 'felt', v3:'felt', trans:'cảm thấy'},
    {id: 60 , v1: 'fight', v2: 'fought', v3:'fought', trans:'chiến đấu'},
    {id: 61 , v1: 'find', v2: 'found', v3:'found', trans:'tìm thấy, thấy'},
    {id: 62 , v1: 'fit', v2: 'fitted/fit', v3:'fitted/fit', trans:'làm cho vừa, làm cho hợp'},
    {id: 63 , v1: 'flee', v2: 'fled', v3:'fled', trans:'chạy trốn'},
    {id: 64 , v1: 'fling', v2: 'flung', v3:'flung', trans:'tung, quăng'},
    {id: 65 , v1: 'fly', v2: 'flew', v3:'flown', trans:'bay'},
    {id: 66 , v1: 'forbear', v2: 'forbore', v3:'forborne', trans:'nhịn'},
    {id: 67 , v1: 'forbid', v2: 'forbade/forbad', v3:'forbidden', trans:'cấm, cấm đoán'},
    {id: 68 , v1: 'forecast', v2: 'forecast/forecasted', v3:'forecast/forecasted', trans:'tiên đoán'},
    {id: 69 , v1: 'forego (also forgo)', v2: 'forewent', v3:'foregone', trans:'bỏ, kiêng'},
    {id: 70 , v1: 'foresee', v2: 'foresaw', v3:'forseen', trans:'thấy trước'},
    {id: 71 , v1: 'foretell', v2: 'foretold', v3:'foretold', trans:'đoán trước'},
    {id: 72 , v1: 'forget', v2: 'forgot', v3:'forgotten', trans:'quên'},
    {id: 73 , v1: 'forgive', v2: 'forgave', v3:'forgiven', trans:'tha thứ'},
    {id: 74 , v1: 'forsake', v2: 'forsook', v3:'forsaken', trans:'ruồng bỏ'},
    {id: 75 , v1: 'freeze', v2: 'froze', v3:'frozen', trans:'(làm) đông lại'},
    {id: 76 , v1: 'frostbite', v2: 'frostbit', v3:'frostbitten', trans:'bỏng lạnh'},
    {id: 77 , v1: 'get', v2: 'got', v3:'got/gotten', trans:'có được'},
    {id: 78 , v1: 'gild', v2: 'gilt/gilded', v3:'gilt/gilded', trans:'mạ vàng'},
    {id: 79 , v1: 'gird', v2: 'girt/girded', v3:'girt/girded', trans:'đeo vào'},
    {id: 80 , v1: 'give', v2: 'gave', v3:'given', trans:'cho'},
    {id: 81 , v1: 'go', v2: 'went', v3:'gone', trans:'đi'},
    {id: 82 , v1: 'grind', v2: 'ground', v3:'ground', trans:'nghiền, xay'},
    {id: 83 , v1: 'grow', v2: 'grew', v3:'grown', trans:'mọc, trồng'},
    {id: 84 , v1: 'hand-feed', v2: 'hand-fed', v3:'hand-fed', trans:'cho ăn bằng tay'},
    {id: 85 , v1: 'handwrite', v2: 'handwrote', v3:'handwritten', trans:'viết tay'},
    {id: 86 , v1: 'hang', v2: 'hung', v3:'hung', trans:'móc lên, treo lên'},
    {id: 87 , v1: 'have', v2: 'had', v3:'had', trans:'có'},
    {id: 88 , v1: 'hear', v2: 'heard', v3:'heard', trans:'nghe'},
    {id: 89 , v1: 'heave', v2: 'hove/heaved', v3:'hove/heaved', trans:'trục lên'},
    {id: 90 , v1: 'hew', v2: 'hewed', v3:'hewn/hewed', trans:'chặt, đốn'},
    {id: 91 , v1: 'hide', v2: 'hid', v3:'hidden', trans:'giấu, trốn, nấp'},
    {id: 92 , v1: 'hit', v2: 'hit', v3:'hit', trans:'đụng'},
    {id: 93 , v1: 'hurt', v2: 'hurt', v3:'hurt', trans:'làm đau'},
    {id: 94 , v1: 'inbreed', v2: 'inbred', v3:'inbred', trans:'lai giống cận huyết'},
    {id: 95 , v1: 'inlay', v2: 'inlaid', v3:'inlaid', trans:'cẩn, khảm'},
    {id: 96 , v1: 'input', v2: 'input', v3:'input', trans:'đưa vào'},
    {id: 97 , v1: 'inset', v2: 'inset', v3:'inset', trans:'dát, ghép'},
    {id: 98 , v1: 'interbreed', v2: 'interbred', v3:'interbred', trans:'giao phối, lai giống'},
    {id: 99 , v1: 'interweave', v2: 'interwove/interweaved', v3:'interwoven/interweaved', trans:'trộn lẫn, xen lẫn'},
    {id: 100 , v1: 'interwind', v2: 'interwound', v3:'interwound', trans:'cuộn vào, quấn vào'},
    {id: 101 , v1: 'jerry-build', v2: 'jerry-built', v3:'jerry-built', trans:'xây dựng cẩu thả'},
    {id: 102 , v1: 'keep', v2: 'kept', v3:'kept', trans:'giữ'},
    {id: 103 , v1: 'kneel', v2: 'knelt/kneeled', v3:'knelt/kneeled', trans:'quỳ'},
    {id: 104 , v1: 'knit', v2: 'knit/knitted', v3:'knit/knitted', trans:'đan'},
    {id: 105 , v1: 'know', v2: 'knew', v3:'known', trans:'biết, quen biết'},
    {id: 106 , v1: 'lay', v2: 'laid', v3:'laid', trans:'đặt, để'},
    {id: 107 , v1: 'lead', v2: 'led', v3:'led', trans:'dẫn dắt, lãnh đạo'},
    {id: 108 , v1: 'lean', v2: 'leaned/leant', v3:'leaned/leant', trans:'dựa, tựa'},
    {id: 109 , v1: 'leap', v2: 'leapt', v3:'leapt', trans:'nhảy, nhảy qua'},
    {id: 110 , v1: 'learn', v2: 'learnt/learned', v3:'learnt/learned', trans:'học, được biết'},
    {id: 111 , v1: 'leave', v2: 'left', v3:'left', trans:'ra đi, để lại'},
    {id: 112 , v1: 'lend', v2: 'lent', v3:'lent', trans:'cho mượn'},
    {id: 113 , v1: 'let', v2: 'let', v3:'let', trans:'cho phép, để cho'},
    {id: 114 , v1: 'lie', v2: 'lay', v3:'lain', trans:'nằm'},
    {id: 115 , v1: 'light', v2: 'lit/lighted', v3:'lit/lighted', trans:'thắp sáng'},
    {id: 116 , v1: 'lip-read', v2: 'lip-read', v3:'lip-read', trans:'mấp máy môi'},
    {id: 117 , v1: 'lose', v2: 'lost', v3:'lost', trans:'làm mất, mất'},
    {id: 118 , v1: 'make', v2: 'made', v3:'made', trans:'chế tạo, sản xuất'},
    {id: 119 , v1: 'mean', v2: 'meant', v3:'meant', trans:'	có nghĩa là'},
    {id: 120 , v1: 'meet', v2: 'met', v3:'met', trans:'gặp mặt'},
    {id: 121 , v1: 'miscast', v2: 'miscast', v3:'miscast', trans:'chọn vai đóng không hợp'},
    {id: 122 , v1: 'misdeal', v2: 'misdealt', v3:'misdealt', trans:'chia lộn bài, chia bài sai'},
    {id: 123 , v1: 'misdo', v2: 'misdid', v3:'misdone', trans:'phạm lỗi'},
    {id: 124 , v1: 'mishear', v2: 'misheard', v3:'misheard', trans:'nghe nhầm'},
    {id: 125 , v1: 'mislay', v2: 'mislaid', v3:'mislaid', trans:'để lạc mất'},
    {id: 126 , v1: 'mislead', v2: 'misled', v3:'misled', trans:'làm lạc đường'},
    {id: 127 , v1: 'mislearn', v2: 'mislearned/mislearnt', v3:'mislearned/mislearnt', trans:'học nhầm'},
    {id: 128 , v1: 'misread', v2: 'misread', v3:'misread', trans:'đọc sai'},
    {id: 129 , v1: 'misset', v2: 'misset', v3:'misset', trans:'đặt sai chỗ'},
    {id: 130 , v1: 'misspeak', v2: 'misspoke', v3:'misspoken', trans:'nói sai'},
    {id: 131 , v1: 'misspell', v2: 'misspelt', v3:'misspelt', trans:'viết sai chính tả'},
    {id: 132 , v1: 'misspend', v2: 'misspent', v3:'misspent', trans:'tiêu phí, bỏ phí'},
    {id: 133 , v1: 'mistake', v2: 'mistook', v3:'mistaken', trans:'phạm lỗi, lầm lẫn'},
    {id: 134 , v1: 'misteach', v2: 'mistaught', v3:'mistaught', trans:'dạy sai'},
    {id: 135 , v1: 'misunderstand', v2: 'misunderstood', v3:'misunderstood', trans:'hiểu lầm'},
    {id: 136 , v1: 'miswrite', v2: 'miswrote', v3:'miswritten', trans:'viết sai'},
    {id: 137 , v1: 'mow', v2: 'mowed', v3:'mown/mowed', trans:'cắt cỏ'},
    {id: 138 , v1: 'offset', v2: 'offset', v3:'offset', trans:'đền bù'},
    {id: 139 , v1: 'outbid', v2: 'outbid', v3:'outbid', trans:'trả hơn giá'},
    {id: 140 , v1: 'outbreed', v2: 'outbred', v3:'outbred', trans:'giao phối xa'},
    {id: 141 , v1: 'outdo', v2: 'outdid', v3:'outdone', trans:'làm giỏi hơn'},
    {id: 142 , v1: 'outdraw', v2: 'outdrew', v3:'outdrawn', trans:'rút súng ra nhanh hơn'},
    {id: 143 , v1: 'outdrink', v2: 'outdrank', v3:'outdrunk', trans:'uống quá chén'},
    {id: 144 , v1: 'outdrive', v2: 'outdrove', v3:'outdriven', trans:'lái nhanh hơn'},
    {id: 145 , v1: 'outfight', v2: 'outfought', v3:'outfought', trans:'đánh giỏi hơn'},
    {id: 146 , v1: 'outfly', v2: 'outflew', v3:'outflown', trans:'bay cao/xa hơn'},
    {id: 147 , v1: 'outgrow', v2: 'outgrew', v3:'outgrown', trans:'lớn nhanh hơn'},
    {id: 148 , v1: 'outleap', v2: 'outleaped/outleapt', v3:'outleaped/outleapt', trans:'nhảy cao/xa hơn'},
    {id: 149 , v1: 'outlie', v2: 'outlied', v3:'outlied', trans:'nói dối'},
    {id: 150 , v1: 'output', v2: 'output', v3:'output', trans:'cho ra (dữ kiện)'},
    {id: 151 , v1: 'outride', v2: 'outrode', v3:'outridden', trans:'cưỡi ngựa giỏi hơn'},
    {id: 152 , v1: 'outrun', v2: 'outran', v3:'outrun', trans:'chạy nhanh hơn, vượt giá'},
    {id: 153 , v1: 'outsell', v2: 'outsold', v3:'outsold', trans:'bán nhanh hơn'},
    {id: 154 , v1: 'outshine', v2: 'outshined/outshone', v3:'outshined/outshone', trans:'sáng hơn, rạng rỡ hơn'},
    {id: 155 , v1: 'outshoot', v2: 'outshot', v3:'outshot', trans:'bắn giỏi hơn, nảy mầm, mọc'},
    {id: 156 , v1: 'outsing', v2: 'outsang', v3:'outsung', trans:'hát hay hơn'},
    {id: 157 , v1: 'outsit', v2: 'outsat', v3:'outsat', trans:'ngồi lâu hơn'},
    {id: 158 , v1: 'outsleep', v2: 'outslept', v3:'outslept', trans:'ngủ lâu/muộn hơn'},
    {id: 159 , v1: 'outsmell', v2: 'outsmelled/outsmelt', v3:'outsmelled/outsmelt', trans:'khám phá, đánh hơi, sặc mùi'},
    {id: 160 , v1: 'outspeak', v2: 'outspoke', v3:'outspoken ', trans:'nói nhiều/dài/to hơn'},
    {id: 161 , v1: 'outspeed', v2: 'outspoke', v3:'outsped', trans:'đi/chạy nhanh hơn'},
    {id: 162 , v1: 'outspend', v2: 'outspent', v3:'outspent', trans:'tiêu tiền nhiều hơn'},
    {id: 163 , v1: 'outswear', v2: 'outswore', v3:'outsworn', trans:'nguyền rủa nhiều hơn'},
    {id: 164 , v1: 'outswim', v2: 'outswam', v3:'outswum', trans:'bơi giỏi hơn'},
    {id: 165 , v1: 'outthink', v2: 'outthought', v3:'outthought', trans:'suy nghĩ nhanh hơn'},
    {id: 166 , v1: 'outthrow', v2: 'outthrew', v3:'outthought', trans:'ném nhanh hơn'},
    {id: 167 , v1: 'outwrite', v2: 'outwrote', v3:'outthrown', trans:'viết nhanh hơn'},
    {id: 168 , v1: 'overbid', v2: 'overbid', v3:'overbid', trans:'trả giá/bỏ thầu cao hơn'},
    {id: 169 , v1: 'overbreed', v2: 'overbred', v3:'overbred', trans:'nuôi quá nhiều'},
    {id: 170 , v1: 'overbuild', v2: 'overbuilt', v3:'overbuilt', trans:'xây quá nhiều'},
    {id: 171 , v1: 'overbuy', v2: 'overbought', v3:'overbought', trans:'mua quá nhiều'},
    {id: 172 , v1: 'overcome', v2: 'overcame', v3:'overcome', trans:'khắc phục'},
    {id: 173 , v1: 'overdo', v2: 'overdid', v3:'overdone', trans:'dùng quá mức, làm quá'},
    {id: 174 , v1: 'overdraw', v2: 'overdrew', v3:'overdrawn', trans:'rút quá số tiền, phóng đại'},
    {id: 175 , v1: 'overdrink', v2: 'overdrank', v3:'overdrunk', trans:'uống quá nhiều'},
    {id: 176 , v1: 'overeat', v2: 'overate', v3:'overeaten', trans:'ăn quá nhiều'},
    {id: 177 , v1: 'overfeed', v2: 'overfed', v3:'overfed', trans:'cho ăn quá mức'},
    {id: 178 , v1: 'overfly', v2: 'overflew', v3:'overflown', trans:'bay qua'},
    {id: 179 , v1: 'overhang', v2: 'overhung', v3:'overhung', trans:'nhô lên trên, treo lơ lửng'},
    {id: 180 , v1: 'overhear', v2: 'overheard', v3:'overheard', trans:'nghe trộm'},
    {id: 181 , v1: 'overlay', v2: 'overlaid', v3:'overlaid', trans:'phủ lên'},
    {id: 182 , v1: 'overpay', v2: 'overpaid', v3:'overpaid', trans:'trả quá tiền'},
    {id: 183 , v1: 'override', v2: 'overrode', v3:'overridden', trans:'lạm quyền'},
    {id: 184 , v1: 'overrun', v2: 'overran', v3:'overrun', trans:'tràn ngập'},
    {id: 185 , v1: 'oversee', v2: 'oversaw', v3:'overseen', trans:'trông nom'},
    {id: 186 , v1: 'oversell', v2: 'oversold', v3:'oversold', trans:'bán quá mức'},
    {id: 187 , v1: 'oversew', v2: 'oversewed', v3:'oversewn/oversewed', trans:'may nối vắt'},
    {id: 188 , v1: 'overshoot', v2: 'overshot', v3:'overshot', trans:'đi quá đích'},
    {id: 189 , v1: 'oversleep', v2: 'overslept', v3:'overslept', trans:'ngủ quên'},
    {id: 190 , v1: 'overspeak', v2: 'overspoke', v3:'overspoken', trans:'Nói quá nhiều, nói lấn át'},
    {id: 191 , v1: 'overspend', v2: 'overspent', v3:'overspent', trans:'tiêu quá lố'},
    {id: 192 , v1: 'overspill', v2: 'overspilled/overspilt', v3:'overspilled/overspilt', trans:'đổ, làm tràn'},
    {id: 193 , v1: 'overtake', v2: 'overtook', v3:'overtaken', trans:'đuổi bắt kịp'},
    {id: 194 , v1: 'overthink', v2: 'overthought', v3:'overthought', trans:'tính trước nhiều quá'},
    {id: 195 , v1: 'overthrow', v2: 'overthrew', v3:'overthrown', trans:'lật đổ'},
    {id: 196 , v1: 'overwind', v2: 'overwound', v3:'overwound', trans:'lên dây (đồng hồ) quá chặt'},
    {id: 197 , v1: 'overwrite', v2: 'overwrote', v3:'overwritten', trans:'viết dài quá, viết đè lên'},
    {id: 198 , v1: 'partake', v2: 'partook', v3:'partaken', trans:'tham gia, dự phần'},
    {id: 199 , v1: 'pay', v2: 'paid', v3:'paid', trans:'trả (tiền)'},
    {id: 200 , v1: 'plead', v2: 'pleaded/pled', v3:'pleaded/pled', trans:'bào chữa, biện hộ'},
    {id: 201 , v1: 'prebuild', v2: 'prebuilt', v3:'prebuilt', trans:'làm nhà tiền chế'},
    {id: 202 , v1: 'predo', v2: 'predid', v3:'predone', trans:'làm trước'},
    {id: 203 , v1: 'premake', v2: 'premade', v3:'premade', trans:'làm trước'},
    {id: 204 , v1: 'prepay', v2: 'prepaid', v3:'prepaid', trans:'trả trước'},
    {id: 205 , v1: 'presell', v2: 'presold', v3:'presold', trans:'bán trước thời gian rao báo'},
    {id: 206 , v1: 'preset', v2: 'preset', v3:'preset', trans:'thiết lập sẵn, cài đặt sẵn'},
    {id: 207 , v1: 'preshrink', v2: 'preshrank', v3:'preshrunk', trans:'ngâm cho vải co trước khi may'},
    {id: 208 , v1: 'proofread', v2: 'proofread', v3:'proofread', trans:'Đọc bản thảo trước khi in'},
    {id: 209 , v1: 'prove', v2: 'proved', v3:'proven/proved', trans:'chứng minh'},
    {id: 210 , v1: 'put', v2: 'put', v3:'put', trans:'đặt, để'},
    {id: 211 , v1: 'quick-freeze', v2: 'quick-froze', v3:'quick-frozen', trans:'kết đông nhanh'},
    {id: 212 , v1: 'quit', v2: 'quit/quitted', v3:'quit/quitted', trans:'bỏ'},
    {id: 213 , v1: 'read', v2: 'read', v3:'read', trans:'đọc'},
    {id: 214 , v1: 'reawake', v2: 'reawoke', v3:'reawaken', trans:'đánh thức 1 lần nữa'},
    {id: 215 , v1: 'rebid', v2: 'rebid', v3:'rebid', trans:'trả giá, bỏ thầu'},
    {id: 216 , v1: 'rebind', v2: 'rebound', v3:'rebound', trans:'buộc lại, đóng lại'},
    {id: 217 , v1: 'rebroadcast', v2: 'rebroadcast/rebroadcasted', v3:'rebroadcast/rebroadcasted', trans:'cự tuyệt, khước từ'},
    {id: 218 , v1: 'rebuild', v2: 'rebuilt', v3:'rebuilt', trans:'xây dựng lại'},
    {id: 219 , v1: 'recast', v2: 'recast', v3:'recast', trans:'đúc lại'},
    {id: 220 , v1: 'recut', v2: 'recut', v3:'recut', trans:'cắt lại, băm'},
    {id: 221 , v1: 'redeal', v2: 'redealt', v3:'redealt', trans:'phát bài lại'},
    {id: 222 , v1: 'redo', v2: 'redid', v3:'redone', trans:'làm lại'},
    {id: 223 , v1: 'redraw', v2: 'redrew', v3:'redrawn', trans:'kéo ngược lại'},
    {id: 224 , v1: 'refit', v2: 'refitted/refit', v3:'refitted/refit', trans:'luồn, xỏ'},
    {id: 225 , v1: 'regrind', v2: 'reground', v3:'reground', trans:'mài sắc lại'},
    {id: 226 , v1: 'regrow', v2: 'regrew', v3:'regrown', trans:'trồng lại'},
    {id: 227 , v1: 'rehang', v2: 'rehung', v3:'rehung', trans:'treo lại'},
    {id: 228 , v1: 'rehear', v2: 'reheard', v3:'reheard', trans:'nghe trình bày lại'},
    {id: 229 , v1: 'reknit', v2: 'reknitted/reknit', v3:'reknitted/reknit', trans:'đan lại'},
    {id: 230 , v1: 'relay', v2: 'relaid', v3:'relaid', trans:'đặt lại'},
    {id: 231 , v1: 'relay', v2: 'relayed', v3:'relayed', trans:'truyền âm lại'},
    {id: 232 , v1: 'relearn', v2: 'relearned/relearnt', v3:'relearned/relearnt', trans:'học lại'},
    {id: 233 , v1: 'relight', v2: 'relit/relighted', v3:'relit/relighted', trans:'thắp sáng lại'},
    {id: 234 , v1: 'remake', v2: 'remade', v3:'remade', trans:'làm lại, chế tạo lại'},
    {id: 235 , v1: 'rend', v2: 'rent', v3:'rent', trans:'toạc ra, xé'},
    {id: 236 , v1: 'repay', v2: 'repaid', v3:'repaid', trans:'hoàn tiền lại'},
    {id: 237 , v1: 'reread', v2: 'reread', v3:'reread', trans:'đọc lại'},
    {id: 238 , v1: 'rerun', v2: 'reran', v3:'rerun', trans:'chiếu lại, phát lại'},
    {id: 239 , v1: 'resell', v2: 'resold', v3:'resold', trans:'bán lại'},
    {id: 240 , v1: 'resend', v2: 'resent', v3:'resent', trans:'gửi lại'},
    {id: 241 , v1: 'reset', v2: 'reset', v3:'reset', trans:'đặt lại, lắp lại'},
    {id: 242 , v1: 'resew', v2: 'resewed', v3:'resewn/resewed', trans:'may/khâu lại'},
    {id: 243 , v1: 'retake', v2: 'retook', v3:'retaken', trans:'chiếm lại, tái chiếm'},
    {id: 244 , v1: 'reteach', v2: 'retaught', v3:'retaught', trans:'dạy lại'},
    {id: 245 , v1: 'retear', v2: 'retore', v3:'retorn', trans:'khóc lại'},
    {id: 246 , v1: 'retell', v2: 'retold', v3:'retold', trans:'kể lại'},
    {id: 247 , v1: 'rethink', v2: 'rethought', v3:'rethought', trans:'suy tính lại'},
    {id: 248 , v1: 'retread', v2: 'retread', v3:'retread', trans:'lại giẫm/đạp lên'},
    {id: 249 , v1: 'retrofit', v2: 'retrofitted/retrofit', v3:'retrofitted/retrofit', trans:'trang bị thêm những bộ phận mới'},
    {id: 250 , v1: 'rewake', v2: 'rewoke/rewaked', v3:'rewaken/rewaked', trans:'đánh thức lại'},
    {id: 251 , v1: 'rewear', v2: 'rewore', v3:'reworn', trans:'mặc lại'},
    {id: 252 , v1: 'reweave', v2: 'rewove/reweaved', v3:'rewove/reweaved', trans:'dệt lại'},
    {id: 253 , v1: 'rewed', v2: 'rewed/rewedded', v3:'rewed/rewedded', trans:'kết hôn lại'},
    {id: 254 , v1: 'rewet', v2: 'rewet/rewetted', v3:'rewet/rewetted', trans:'làm ướt lại'},
    {id: 255 , v1: 'rewin', v2: 'rewon', v3:'rewon', trans:'thắng lại'},
    {id: 256 , v1: 'rewind', v2: 'rewound', v3:'rewound', trans:'cuốn lại, lên dây lại'},
    {id: 257 , v1: 'rewrite', v2: 'rewrote', v3:'rewritten', trans:'viết lại'},
    {id: 258 , v1: 'rid', v2: 'rid', v3:'rid', trans:'giải thoát'},
    {id: 259 , v1: 'ride', v2: 'rode', v3:'ridden', trans:'cưỡi'},
    {id: 260 , v1: 'ring', v2: 'rang', v3:'rung', trans:'rung chuông'},
    {id: 261 , v1: 'rise', v2: 'rose', v3:'risen', trans:'đứng dậy, mọc'},
    {id: 262 , v1: 'roughcast', v2: 'roughcast', v3:'roughcast', trans:'tạo hình phỏng chừng '},
    {id: 263 , v1: 'run', v2: 'ran', v3:'run', trans:'chạy'},
    {id: 264 , v1: 'sand-cast', v2: 'sand-cast', v3:'sand-cast', trans:'đúc bằng khuôn cát'},
    {id: 265 , v1: 'saw', v2: 'sawed', v3:'sawn', trans:'cưa'},
    {id: 266 , v1: 'say', v2: 'said', v3:'said', trans:'nói'},
    {id: 267 , v1: 'see', v2: 'saw', v3:'seen', trans:'nhìn thấy'},
    {id: 268 , v1: 'seek', v2: 'sought', v3:'sought', trans:'tìm kiếm'},
    {id: 269 , v1: 'sell', v2: 'sold', v3:'sold', trans:'bán'},
    {id: 270 , v1: 'send', v2: 'sent', v3:'sent', trans:'gửi'},
    {id: 271 , v1: 'set', v2: 'set', v3:'set', trans:'đặt, thiết lập'},
    {id: 272 , v1: 'sew', v2: 'sewed', v3:'sewn/sewed', trans:'may'},
    {id: 273 , v1: 'shake', v2: 'shook', v3:'shaken', trans:'lay, lắc'},
    {id: 274 , v1: 'shave', v2: 'shaved', v3:'shaved/shaven', trans:'cạo (râu, mặt)'},
    {id: 275 , v1: 'shear', v2: 'sheared', v3:'shorn', trans:'xén lông (cừu)'},
    {id: 276 , v1: 'shed', v2: 'shed', v3:'shed', trans:'rơi, rụng'},
    {id: 277 , v1: 'shine', v2: 'shone', v3:'shone', trans:'chiếu sáng'},
    {id: 278 , v1: 'shit', v2: 'shit/shat/shitted', v3:'shit/shat/shitted', trans:'suộc khuộng đi đại tiện'},
    {id: 279 , v1: 'shoot', v2: 'shot', v3:'shot', trans:'bắn'},
    {id: 280 , v1: 'show', v2: 'showed', v3:'shown/showed', trans:'cho xem'},
    {id: 281 , v1: 'shrink', v2: 'shrank', v3:'shrunk', trans:'co rút'},
    {id: 282 , v1: 'shut', v2: 'shut', v3:'shut', trans:'đóng lại'},
    {id: 283 , v1: 'sight-read', v2: 'sight-read', v3:'sight-read', trans:'chơi hoặc hát mà không cần nghiên cứu trước'},
    {id: 284 , v1: 'sing', v2: 'sang', v3:'sung', trans:'ca hát'},
    {id: 285 , v1: 'sink', v2: 'sank', v3:'sunk', trans:'chìm, lặn'},
    {id: 286 , v1: 'sit', v2: 'sat', v3:'sat', trans:'ngồi'},
    {id: 287 , v1: 'slay', v2: 'slew', v3:'slain', trans:'sát hại, giết hại'},
    {id: 288 , v1: 'sleep', v2: 'slept', v3:'slept', trans:'ngủ'},
    {id: 289 , v1: 'slide', v2: 'slid', v3:'slid', trans:'trượt, lướt'},
    {id: 290 , v1: 'sling', v2: 'slung', v3:'slung', trans:'ném mạnh'},
    {id: 291 , v1: 'slink', v2: 'slunk', v3:'slunk', trans:'lẻn đi'},
    {id: 292 , v1: 'slit', v2: 'slit', v3:'slit', trans:'rạch, khứa'},
    {id: 293 , v1: 'smell', v2: 'smelt', v3:'smelt', trans:'ngửi'},
    {id: 294 , v1: 'smite', v2: 'smote', v3:'smitten', trans:'đập mạnh'},
    {id: 295 , v1: 'sneak', v2: 'sneaked/snuck', v3:'sneaked/snuck', trans:'trốn, lén'},
    {id: 296 , v1: 'speak', v2: 'spoke', v3:'spoken', trans:'nói'},
    {id: 297 , v1: 'speed', v2: 'sped/speeded', v3:'sped/speeded', trans:'chạy vụt'},
    {id: 298 , v1: 'spell', v2: 'spelt/spelled', v3:'spelt/spelled', trans:'đánh vần'},
    {id: 299 , v1: 'spend', v2: 'spent', v3:'spent', trans:'tiêu xài'},
    {id: 300 , v1: 'spill', v2: 'spilt/spilled', v3:'spilt/spilled', trans:'tràn, đổ ra'},
    {id: 301 , v1: 'spin', v2: 'spun/span', v3:'spun', trans:'quay sợi'},
    {id: 302 , v1: 'spoil', v2: 'spoilt/spoiled', v3:'spoilt/spoiled', trans:'làm hỏng'},
    {id: 303 , v1: 'spread', v2: 'spread', v3:'spread', trans:'lan truyền'},
    {id: 304 , v1: 'stand', v2: 'stood', v3:'stood', trans:'đứng'},
    {id: 305 , v1: 'steal', v2: 'stole', v3:'stolen', trans:'đánh cắp'},
    {id: 306 , v1: 'stick', v2: 'stuck', v3:'stuck', trans:'ghim vào, đính'},
    {id: 307 , v1: 'sting', v2: 'stung', v3:'stung', trans:'châm, chích, đốt'},
    {id: 308 , v1: 'stink', v2: 'stunk/stank', v3:'stunk', trans:'bốc mùi hôi'},
    {id: 309 , v1: 'stride', v2: 'strode', v3:'stridden', trans:'bước sải'},
    {id: 310 , v1: 'strike', v2: 'struck', v3:'struck', trans:'đánh đập'},
    {id: 311 , v1: 'string', v2: 'strung', v3:'strung', trans:'gắn dây vào'},
    {id: 312 , v1: 'sunburn', v2: 'sunburned/sunburnt', v3:'sunburned/sunburnt', trans:'cháy nắng'},
    {id: 313 , v1: 'swear', v2: 'swore', v3:'sworn', trans:'tuyên thệ'},
    {id: 314 , v1: 'sweat', v2: 'sweat/sweated', v3:'sweat/sweated', trans:'đổ mồ hôi'},
    {id: 315 , v1: 'sweep', v2: 'swept', v3:'swept', trans:'quét'},
    {id: 316 , v1: 'swell', v2: 'swelled', v3:'swelled', trans:'phồng, sưng'},
    {id: 317 , v1: 'swim', v2: 'swam', v3:'swum', trans:'bơi lội'},
    {id: 318 , v1: 'swing', v2: 'swung', v3:'swung', trans:'đong đưa'},
    {id: 319 , v1: 'take', v2: 'took', v3:'taken', trans:'cầm, lấy'},
    {id: 320 , v1: 'teach', v2: 'taught', v3:'taught', trans:'dạy, giảng dạy'},
    {id: 321 , v1: 'tear', v2: 'tore', v3:'torn', trans:'xé, rách'},
    {id: 322 , v1: 'telecast', v2: 'telecast', v3:'telecast', trans:'phát đi bằng truyền hình'},
    {id: 323 , v1: 'tell', v2: 'told', v3:'told', trans:'kể, bảo'},
    {id: 324 , v1: 'think', v2: 'thought', v3:'thought', trans:'suy nghĩ'},
    {id: 325 , v1: 'throw', v2: 'threw', v3:'thrown', trans:'ném,, liệng'},
    {id: 326 , v1: 'thrust', v2: 'thrust', v3:'thrust', trans:'thọc, nhấn'},
    {id: 327 , v1: 'tread', v2: 'trod', v3:'trodden/trod', trans:'giẫm, đạp'},
    {id: 328 , v1: 'typewrite', v2: 'typewrote', v3:'typewritten', trans:'đánh máy'},
    {id: 329 , v1: 'unbend', v2: 'unbent', v3:'unbent', trans:'làm thẳng lại'},
    {id: 330 , v1: 'unbind', v2: 'unbound', v3:'unbound', trans:'mở, tháo ra'},
    {id: 331 , v1: 'unclothe', v2: 'unclothed/unclad', v3:'unclothed/unclad', trans:'ởi áo, lột trần'},
    {id: 332 , v1: 'undercut', v2: 'undercut', v3:'undercut', trans:'ra giá rẻ hơn'},
    {id: 333 , v1: 'underfeed', v2: 'underfed', v3:'underfed', trans:'cho ăn đói, thiếu ăn'},
    {id: 334 , v1: 'undergo', v2: 'underwent', v3:'undergone', trans:'inh qua'},
    {id: 335 , v1: 'underlie', v2: 'underlay', v3:'underlain', trans:'nằm dưới'},
    {id: 336 , v1: 'understand', v2: 'understood', v3:'understood', trans:'hiểu'},
    {id: 337 , v1: 'undertake', v2: 'undertook', v3:'undertaken', trans:'đảm nhận'},
    {id: 338 , v1: 'underwrite', v2: 'underwrote', v3:'underwritten', trans:'bảo hiểm'},
    {id: 339 , v1: 'undo', v2: 'undid', v3:'undone', trans:'tháo ra'},
    {id: 340 , v1: 'unfreeze', v2: 'unfroze', v3:'unfrozen', trans:'làm tan đông'},
    {id: 341 , v1: 'unhang', v2: 'unhung', v3:'unhung', trans:'hạ xuống, bỏ xuống'},
    {id: 342 , v1: 'unhide', v2: 'unhid', v3:'unhidden', trans:'hiển thị, không ẩn'},
    {id: 343 , v1: 'unlearn', v2: 'unlearned/unlearnt', v3:'unlearned/unlearnt', trans:'gạt bỏ, quên'},
    {id: 344 , v1: 'unspin', v2: 'unspun', v3:'unspun', trans:'quay ngược'},
    {id: 345 , v1: 'unwind', v2: 'unwound', v3:'unwound', trans:'tháo ra'},
    {id: 346 , v1: 'uphold', v2: 'upheld', v3:'upheld', trans:'ủng hộ'},
    {id: 347 , v1: 'upset', v2: 'upset', v3:'upset', trans:'đánh đổ, lật đổ'},
    {id: 348 , v1: 'wake', v2: 'woke/waked', v3:'woken/waked', trans:'thức giấc'},
    {id: 349 , v1: 'wear', v2: 'wore', v3:'worn', trans:'mặc'},
    {id: 350 , v1: 'wed', v2: 'wed/wedded', v3:'wed/wedded', trans:'kết hôn'},
    {id: 351 , v1: 'weep', v2: 'wept', v3:'wept', trans:'khóc'},
    {id: 352 , v1: 'wet', v2: 'wet/wetted', v3:'wet/wetted', trans:'làm ướt'},
    {id: 353 , v1: 'win', v2: 'won', v3:'won', trans:'chiến thắng'},
    {id: 354 , v1: 'wind', v2: 'wound', v3:'wound', trans:'quấn'},
    {id: 355 , v1: 'withdraw', v2: 'withdrew', v3:'withdrawn', trans:'rút lui'},
    {id: 356 , v1: 'withhold', v2: 'withheld', v3:'withheld', trans:'từ khước'},
    {id: 357 , v1: 'withstand', v2: 'withstood', v3:'withstood', trans:'cầm cự'},
    {id: 358 , v1: 'work', v2: 'worked', v3:'worked', trans:'rèn, nhào nặn đất'},
    {id: 359 , v1: 'wring', v2: 'wrung', v3:'wrung', trans:'vặn, siết chặt'},
    {id: 360 , v1: 'write', v2: 'wrote', v3:'written', trans:'viết'},
]
export default data