const data = [
    {
        header: ['Tên', 'Màu sắc'],
        title1: ['Kim loại kiềm và kiềm thổ'],
        mauSac1: [
            ['KMnO4', 'tinh thể màu đỏ tím'],
            ['K2MnO4', 'lục thẫm'],
            ['NaCl', 'không màu, nhưng muối ăn có màu trắng do có lẫn MgCl2 và CaCl2'],
            ['Ca(OH)2', 'kết tủa trắng'],
            ['CaC2O4', 'trắng'],
        ],

        title2: ['Nhôm'],
        mauSac2: [
            ['Al2O3', 'trắng'],
            ['AlCl3', 'dung dịch không màu, tinh thể màu trắng, thường ngã vàng nhạt vì lẫn FeCl3'],
            ['Al(OH)3', 'kết tủa trắng'],
            ['Al2(SO4)3', 'trắng'],
        ],

        title3: ['Sắt'],
        mauSac3: [
            ['Fe', 'màu trắng xám'],
            ['FeS', 'màu đen'],
            ['Fe(OH)2', 'kết tủa trắng xanh'],
            ['Fe(OH)3', 'nâu đỏ, kết tủa nâu đỏ'],
            ['FeCl2', 'dung dịch lục nhạt'],
            ['Fe3O4 (rắn)', 'màu nâu đen'],
            ['FeCl3', 'dung dịch vàng nâu'],
            ['Fe2O3', 'đỏ'],
            ['FeO', 'đen'],
            ['FeSO4.7H2O', 'xanh lục'],
            ['Fe(SCN)3', 'đỏ nâu'],
        ],

        title4: ['Đồng'],
        mauSac4: [
            ['Cu', 'màu đỏ'],
            ['Cu(NO3)2', 'dung dịch xanh lam'],
            ['CuCl2', 'tinh thể nâu, dung dịch xanh lá cây'],
            ['CuSO4', 'tinh thể khan màu trắng, thể thể ngậm nước màu xanh lam, dung dịch xanh lam'],
            ['Cu2O', 'đỏ gạch'],
            ['Cu(OH)2', 'kết tủa xanh lơ (xanh da trời)'],
            ['CuO', 'màu đen'],
            ['Phức của Cu2+', 'luôn màu xanh'],
        ],

        title5: ['Mangan'],
        mauSac5: [
            ['MnCl2', 'dung dịch: xanh lục; tinh thể: đỏ nhạt'],
            ['MnO2', 'kết tủa màu đen'],
            ['Mn(OH)4', 'nâu'],
        ],

        title6: ['Kẽm'],
        mauSac6: [
            ['ZnCl2', 'bột trắng'],
            ['Zn3P2', 'tinh thể nâu xám'],
            ['ZnSO4', 'dung dịch không màu'],
        ],

        title7: ['Crom'],
        mauSac7: [
            ['CrO3', 'đỏ sẫm chromium'],
            ['Cr2O3', 'màu lục'],
            ['CrCl2', 'lục sẫm'],
            ['K2Cr2O7', 'đỏ cam'],
            ['K2CrO4', 'vàng cam'],
        ],

        title8: ['Bạc'],
        mauSac8: [
            ['Ag3PO4', 'kết tủa vàng'],
            ['AgCl', 'trắng'],
            ['Ag2CrO4', 'đỏ gạch'],
        ],

        title9: ['Các hợp chất khác'],
        mauSac9: [
            ['As2S3', 'vàng'],
            ['As2S5', 'vàng'],
            ['B12C3', 'màu đen'],
            ['Ga(OH)3', 'kết tủa nhày, màu trắng'],
            ['GaOOH', 'kết tủa nhày, màu trắng'],
            ['GaI3', 'màu vàng'],
            ['InI3', 'màu vàng'],
            ['In(OH)3', 'kết tủa nhày, màu trắng'],
            ['Tl(OH)3', 'kết tủa nhày, màu hung đỏ'],
            ['TlOOH', 'kết tủa nhày, màu hung đỏ'],
            ['TlI3', 'màu đen'],
            ['Tl2O', 'bột màu đen'],
            ['TlOH', 'dàng tinh thể màu vàng'],
            ['PbI2', 'vàng tươi, tan nhiều trong nước'],
            ['Au2O3', 'nâu đen'],
            ['Hg2I2', 'vàng lục'],
            ['Hg2CrO4', 'đỏ'],
            ['P2O5', 'chất rắn màu trắng'],
            ['NO', 'hóa nâu trong không khí'],
            ['NH3', 'làm quỳ tím ẩm hóa xanh'],
            ['Kết tủa trinitrat toluen', 'màu vàng'],
            ['Kết tủa trinitrat phenol', 'màu trắng'],
        ],

        title10: ['Màu của ngọn lửa'],
        mauSac10: [
            ['Muối của Li', 'màu đỏ tía'],
            ['Muối của Na', 'màu vàng'],
            ['Muối của K', 'màu tím'],
            ['Muối của Ba', 'lục vàng'],
            ['Muối của Ca', 'màu cam'],
        ],

        title11: ['Màu sắc của kim loại khi cháy được ứng dụng làm pháo hoa'],
        mauSac11: [
            ['Li', 'màu trắng bạc'],
            ['Na', 'màu trắng bạc'],
            ['Mg', 'màu trắng bạc'],
            ['K', 'có màu trắng bạc khi bề mặt sạch'],
            ['Ca', 'màu xám bạc'],
            ['B', 'có hai dạng thù hình của Bo; Bo vô định hình là chất bột màu nâu, nhưng Bo kim loại thì có màu đen'],
            ['N', 'chất khí ở dạng phân tử không màu'],
            ['O', 'khí không màu'],
            ['F', 'khí màu vàng lục nhạt'],
            ['Al', 'màu trắng bạc'],
            ['Si', 'màu xám sẵm ánh xanh'],
            ['P', 'tồn tại dưới ba dạng thù hình cơ bản có màu: trắng, đỏ và đen'],
            ['S', 'màu vàng chanh'],
            ['Cl', 'màu vàng lục nhạt'],
            ['I', 'màu tím than'],
            ['Cr', 'màu trắng bạc'],
            ['Mn', 'kim loạimàu trắng bạc'],
            ['Fe', 'kim loại màu xám nhẹ ánh kim'],
            ['Cu', 'kim loại có màu vàng ánh đỏ'],
            ['Zn', 'kim loại màu xám nhạt ánh lam'],
            ['Ba', 'kim loại trắng bạc'],
            ['Hg', 'kim loại trắng bạc'],
            ['Pb', 'kim loại trắng xám'],
        ],

        title12: ['Màu của ion trong dung dịch'],
        mauSac12: [
            ['Mn2+', 'vàng nhạt'],
            ['Zn2+', 'trắng'],
            ['Al3+', 'trắng'],
            ['Cu2+', 'có màu xanh lam'],
            ['Cu+', 'có màu đỏ gạch'],
            ['Fe3+', 'màu đỏ nâu'],
            ['Fe2+', 'màu trắng xanh'],
            ['Ni2+', 'lục nhạt'],
            ['Cr3+', 'màu lục'],
            ['Co2+', 'màu hồng'],
            ['MnO4-', 'màu tím'],
            ['CrO4 2-', 'màu vàng'],
        ],

        title13: ['Các nhận dạng khác theo màu sắc'],
        mauSac13: [
            ['CuS', 'đen'],
            ['FeS', 'đen'],
            ['Fe2S3', 'đen'],
            ['Ag2S', 'đen'],
            ['PbS', 'đen'],
            ['HgS', 'đen'],
            ['MnS', 'hồng'],
            ['SnS', 'nâu'],
            ['ZnS', 'trắng'],
            ['BaSO4', 'trắng'],
            ['SrSO4', 'trắng'],
            ['CaSO4', 'trắng'],
            ['PbSO4', 'trắng'],
            ['ZnS[NH2Hg]Cl', 'trắng'],
            ['CdS', 'vàng'],
            ['BaCrO4', 'vàng'],
            ['PbCrO4', 'vàng'],
            ['(NH4)3[PMo12O40]', 'vàng'],
            ['(NH4)3[P(Mo2O7)4]', 'vàng'],
            ['AgI', 'vàng nhạt'],
        ],
    }
]

export default data